/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3 */

#ifndef PB_TTGO_PROTO_PROTOS_MEASUREMENTS_PB_H_INCLUDED
#define PB_TTGO_PROTO_PROTOS_MEASUREMENTS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ttgo_proto_Measurements {
    uint32_t error_code;
    float lux;
    float humidity;
    float temperature_C;
    float soil;
    float salt;
    float battery_mV;
    uint32_t timestamp;
    uint32_t fw_version_major;
    uint32_t fw_version_minor;
    uint32_t fw_version_patch;
    uint32_t num_dht_failed_reads;
} ttgo_proto_Measurements;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ttgo_proto_Measurements_init_default     {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define ttgo_proto_Measurements_init_zero        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ttgo_proto_Measurements_error_code_tag   1
#define ttgo_proto_Measurements_lux_tag          2
#define ttgo_proto_Measurements_humidity_tag     3
#define ttgo_proto_Measurements_temperature_C_tag 4
#define ttgo_proto_Measurements_soil_tag         5
#define ttgo_proto_Measurements_salt_tag         6
#define ttgo_proto_Measurements_battery_mV_tag   7
#define ttgo_proto_Measurements_timestamp_tag    8
#define ttgo_proto_Measurements_fw_version_major_tag 9
#define ttgo_proto_Measurements_fw_version_minor_tag 10
#define ttgo_proto_Measurements_fw_version_patch_tag 11
#define ttgo_proto_Measurements_num_dht_failed_reads_tag 12

/* Struct field encoding specification for nanopb */
#define ttgo_proto_Measurements_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   error_code,        1) \
X(a, STATIC,   SINGULAR, FLOAT,    lux,               2) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity,          3) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature_C,     4) \
X(a, STATIC,   SINGULAR, FLOAT,    soil,              5) \
X(a, STATIC,   SINGULAR, FLOAT,    salt,              6) \
X(a, STATIC,   SINGULAR, FLOAT,    battery_mV,        7) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         8) \
X(a, STATIC,   SINGULAR, UINT32,   fw_version_major,   9) \
X(a, STATIC,   SINGULAR, UINT32,   fw_version_minor,  10) \
X(a, STATIC,   SINGULAR, UINT32,   fw_version_patch,  11) \
X(a, STATIC,   SINGULAR, UINT32,   num_dht_failed_reads,  12)
#define ttgo_proto_Measurements_CALLBACK NULL
#define ttgo_proto_Measurements_DEFAULT NULL

extern const pb_msgdesc_t ttgo_proto_Measurements_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ttgo_proto_Measurements_fields &ttgo_proto_Measurements_msg

/* Maximum encoded size of messages (where known) */
#define ttgo_proto_Measurements_size             66

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
